Lab03: main.o 
	g++ -std=c++11 -g -Wall main.o -o Lab03
main.o: main.cpp Node.h Node.hpp DoubleLinkedList.h DoubleLinkedList.hpp 
	g++ -std=c++11 -g -Wall -c main.cpp
clean: 
	rm *.o Lab03
	echo clean done
	 
